AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,GET,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: main
      Runtime: go1.x
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Events:
        GetTodos:
          Type: Api
          Properties:
            Path: /api/task
            Method: GET
        PutTodo:
          Type: Api
          Properties:
            Path: /api/task
            Method: POST
        DeleteTodo:
          Type: Api
          Properties:
            Path: /api/deleteTask/{id}
            Method: DELETE
        UpdateTodo:
          Type: Api
          Properties:
            Path: /api/task/{id}
            Method: PUT
        UndoTodo:
          Type: Api
          Properties:
            Path: /api/undoTask/{id}
            Method: PUT
    Metadata:
      BuildMethod: makefile

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Todos
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: "DoNotNuke"
          Value: "true"
